"""Neutral result tables and figures from the aggregate JSONs (spec 16.1 deliverables).

Usage: python -m auditory_alignment.report
Writes docs/auditory_alignment_kernel_cs/{FULL_RESULTS, OPTIMIZATION_RESULTS, TEMPORAL_RESULTS, GROUP_DEVELOPMENT_RESULTS}.md and
docs/auditory_alignment_kernel_cs/FIGURES/*.png. Group-level numbers only.
"""
from __future__ import annotations

import json
import os
from collections import defaultdict

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(REPO, "results", "auditory_alignment_kernel_cs")
DOC = os.path.join(REPO, "docs", "auditory_alignment_kernel_cs")
FIG = os.path.join(DOC, "FIGURES")
OBJ = ("NCE", "FMCA", "CS_SINGLE", "CS_MULTI")
DSN = {"fau": "FAU/TUD", "dtu": "DTU", "federici": "Federici", "private_bdf": "Private BDF"}
MAIN_T = {"fau": "local", "dtu": "local", "federici": "envelope", "private_bdf": "current_class"}
WINS = ("full", "early", "late", "joint")


def f(b, d=4):
    if not b or b.get("est") is None:
        return "–"
    s = f"{b['est']:+.{d}f}"
    if "ci_low" in b:
        s += f" [{b['ci_low']:+.{d}f}, {b['ci_high']:+.{d}f}]"
    return s


def fp(b, d=3):
    if not b or b.get("est") is None:
        return "–"
    return f"{b['est']:.{d}f}" + (f" [{b['ci_low']:.{d}f}, {b['ci_high']:.{d}f}]" if "ci_low" in b else "")


def key(block, ds, obj, tgt, win, var="default"):
    return "|".join((block, ds, obj, tgt, win, var))


def cov(full, k):
    c = full.get(k)
    return f"{c['n_units']}/{c['n_units_planned']}" if c else "0"


def g(full, k, grp, m):
    c = full.get(k)
    return c["groups"].get(grp, {}).get(m) if c else None


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(map(str, r)) + " |" for r in rows]
    return "\n".join(out)


def targets_of(full, ds):
    return sorted({k.split("|")[3] for k in full if k.split("|")[1] == ds and k.startswith("core|")})


def full_results(full, C, man):
    L = ["# Kernel CS-QMI full round: core results (E1–E4, E6, E8 wrong pairing)", "",
         "Generated by `python -m auditory_alignment.report` from `results/auditory_alignment_kernel_cs/*.json`; neutral tables, no interpretation.",
         "Intervals are participant bootstraps conditional on the fitted models (spec §12); training variance is in the unit-level columns.",
         "`gain_bits` = log loss (mismatched EEG) − log loss (true EEG) over the same real candidates, in bits per 5 s query; >0 means the EEG identifies the heard segment better than another segment's EEG of the same participant.",
         "Coverage `a/b` = completed / planned fit units of the configuration.", "",
         "## 0. Coverage", "", table(["block|dataset", "complete", "not complete", "failed"],
                                     [[k, v.get("complete", 0), v.get("not_complete", 0), v.get("failed", 0)] for k, v in man["by_block_dataset"].items()]),
         "", f"Rejected units (code hash outside the fleet set): {man.get('rejected_units_by_code_hash')}", ""]
    for ds in ("fau", "dtu", "federici"):
        L += [f"## 1.{('fau','dtu','federici').index(ds)+1} {DSN[ds]}: real-candidate retrieval (all test participants)", ""]
        for rd in ("unified", "native"):
            rows = []
            for t in targets_of(full, ds):
                for w in WINS:
                    if not any(key("core", ds, o, t, w) in full for o in OBJ):
                        continue
                    rows.append([f"{t} / {w}"] + [f"{f(g(full, key('core', ds, o, t, w), 'all', f'{rd}/gain_bits'), 3)} ({cov(full, key('core', ds, o, t, w))})" for o in OBJ])
            L += [f"**{rd} readout, gain_bits**", "", table(["target / window"] + list(OBJ), rows), ""]
        rows = []
        for t in targets_of(full, ds):
            k0 = [key("core", ds, o, t, "full") for o in OBJ]
            rows.append([t] + [f"{fp(g(full, k, 'all', 'unified/regular/top1'))} / {fp(g(full, k, 'all', 'native/regular/top1'))} (mm {fp(g(full, k, 'all', 'native/mismatched_eeg/top1'))})" for k in k0])
        L += ["**top-1 (full window): unified / native (native with mismatched EEG)**", "", table(["target"] + list(OBJ), rows), ""]
        rows = []
        for t in targets_of(full, ds):
            rows.append([t] + [f"{f(g(full, key('core', ds, o, t, 'full'), 'all', 'unified/hard_gain_bits'), 3)}" for o in OBJ])
        L += ["**hard candidates (8 nearest real segments, same story/speaker key, other part): log2(9) − log loss, unified**", "",
              table(["target"] + list(OBJ), rows), ""]
    L += ["## 1.4 Private BDF: class representation (current standard/deviant)", ""]
    for m, lab in (("head_gain_vs_base_bits", "calibrated head gain over base rate, bits/trial"), ("head_auc", "head AUC"),
                   ("hist_minus_twin_bits", "history gain minus mismatched-EEG twin, bits/trial"),
                   ("hist_minus_twin_common_support", "same, common-support trials")):
        rows = [[w] + [f"{f(g(full, key('core', 'private_bdf', o, 'current_class', w), 'all', m), 4)} ({cov(full, key('core', 'private_bdf', o, 'current_class', w))})" for o in OBJ] for w in WINS]
        L += [f"**{lab}**", "", table(["window"] + list(OBJ), rows), ""]
    L += ["## 1.5 Linear reference (extension E9, spec §5.4): raw EEG window → ridge bridge, same protocol, no training", "",
          "Unified readout only (its native readout bridges into the raw, unnormalised target, where the candidate-norm bias makes it uninformative). "
          "Paired difference = deep method − linear reference on the same participants.", ""]
    rows = []
    for ds in DSN:
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        for t in (targets_of(full, ds) if ds != "private_bdf" else ["current_class"]):
            for w in WINS:
                kl = key("linear_reference", ds, "LINEAR", t, w)
                if kl not in full:
                    continue
                rows.append([f"{DSN[ds]} {t}/{w}", f"{f(g(full, kl, 'all', m), 3)} ({cov(full, kl)})"] +
                            [f((C.get("vs_linear_reference", {}).get(f"{key('core', ds, o, t, w)} MINUS LINEAR") or {}).get(m, {}).get("all"), 3) for o in OBJ])
    L += [table(["cell", "linear reference"] + [f"{o} − linear" for o in OBJ], rows), ""]
    if C.get("ext_combo"):
        L += ["## 1.6 Summed objectives (extension E10): combination minus each single-objective core model, Local / full", ""]
        rows = []
        for k, v in sorted(C["ext_combo"].items()):
            a, b = k.split(" MINUS ")
            q = a.split("|")
            rows.append([f"{DSN[q[1]]} {q[2]}", b.replace("core_", ""), f(g(full, a, "all", "unified/gain_bits"), 3) + f" ({cov(full, a)})",
                         f((v or {}).get("unified/gain_bits", {}).get("all"), 3), f((v or {}).get("native/gain_bits", {}).get("all"), 3)])
        L += [table(["combination", "minus", "combination unified gain_bits", "Δ unified", "Δ native"], rows), ""]
    if C.get("ext_class_balanced"):
        L += ["## 1.7 Private class-balanced training (extension E11) minus natural-distribution training", ""]
        rows = []
        for k, v in sorted(C["ext_class_balanced"].items()):
            q = k.split(" MINUS ")[0].split("|")
            rows.append([f"{q[2]} {q[4]}", f(g(full, k.split(" MINUS ")[0], "all", "head_gain_vs_base_bits"), 4) + f" ({cov(full, k.split(' MINUS ')[0])})",
                         f((v or {}).get("head_gain_vs_base_bits", {}).get("all"), 4), f((v or {}).get("head_auc", {}).get("all"), 4),
                         f((v or {}).get("hist_minus_twin_bits", {}).get("all"), 4)])
        L += [table(["method window", "balanced head gain", "Δ head gain", "Δ head AUC", "Δ (history − twin)"], rows), ""]
    L += ["## 2. Kernel dependence on test data (spec §10.3)", "",
          "CS-QMI(true) − CS-QMI(legal mismatch), nats, at each unit's training bandwidths; interpretation material, not comparable across datasets.", ""]
    rows = []
    for ds in DSN:
        for w in ("full",):
            rows.append([f"{DSN[ds]} {MAIN_T[ds]}/{w}"] + [f(g(full, key("core", ds, o, MAIN_T[ds], w), "all", "kernel_cs_diff"), 4) for o in OBJ])
    L += [table(["cell"] + list(OBJ), rows), ""]
    L += ["## 3. Paired method differences (same participants; row method minus column method)", ""]
    for ds in DSN:
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        rows = []
        for k, v in C["methods"].items():
            a, b = k.split(" MINUS ")
            q = a.split("|")
            if q[1] != ds or q[3] != MAIN_T[ds] or q[4] != "full" or not v:
                continue
            rows.append([f"{q[2]} − {b}", f(v.get(m, {}).get("all"), 4)])
        L += [f"**{DSN[ds]}, {MAIN_T[ds]} full, {m}**", "", table(["contrast", "all participants"], rows), ""]
    L += ["## 4. Training-side wrong pairing (E8): core model minus wrong-pair model", ""]
    rows = []
    for k, v in C["wrong_pair"].items():
        q = k.split(" MINUS ")[1].split("|")
        m = "unified/gain_bits" if q[1] != "private_bdf" else "head_gain_vs_base_bits"
        rows.append([f"{DSN[q[1]]} {q[2]} {q[3]}/{q[4]}", m, f((v or {}).get(m, {}).get("all"), 4)])
    L += [table(["cell", "metric", "core − wrong pair"], rows), ""]
    L += ["## 5. Attention 2AFC (E6): accuracy of the attended over the ignored stream", ""]
    rows = []
    for ds in ("fau", "dtu"):
        for t in ("local", "Lz"):
            for o in OBJ:
                kc, ka = key("core", ds, o, t, "full"), key("attention", ds, o, t, "full", "training_task=competing_speech_attended_alignment")
                rows.append([f"{DSN[ds]} {t} {o}", fp(g(full, kc, "all", "attention/unified/accuracy")), fp(g(full, ka, "all", "attention/unified/accuracy")),
                             fp(g(full, ka, "all", "attention/native/accuracy")), cov(full, ka)])
    L += [table(["cell", "zero-shot (single-speaker model), unified", "attention-trained, unified", "attention-trained, native", "coverage"], rows), ""]
    L += ["## 6. Split-half reliability (spec §10.5; first vs second half of each recording)", ""]
    rows = []
    for ds in DSN:
        for o in OBJ:
            k = key("core", ds, o, MAIN_T[ds], "full")
            rel = (full.get(k) or {}).get("split_half_reliability", {})
            rows.append([f"{DSN[ds]} {o}"] + [fp({"est": v["split_half_r"], "ci_low": v["ci_low"], "ci_high": v["ci_high"]}, 2) + f" (n={v['n']})" for v in rel.values()] + [""] * (2 - len(rel)))
    L += [table(["cell", "reliability 1", "reliability 2"], rows), "", "(columns: unified then native rank percentile for speech; head gain then history gain for the private task)",
          "Raw rank percentiles per half can be driven by which stimulus content a participant's halves contain; the EEG-specific version follows (post-hoc R1).", ""]
    rows = []
    for ds in ("fau", "dtu", "federici"):
        for t in targets_of(full, ds):
            for o in OBJ:
                rel = (full.get(key("core", ds, o, t, "full")) or {}).get("split_half_reliability_gain_R1", {})
                if rel:
                    rows.append([f"{DSN[ds]} {t} {o}"] + [fp({"est": rel[m]["split_half_r"], "ci_low": rel[m]["ci_low"], "ci_high": rel[m]["ci_high"]}, 2)
                                                          + f" (SB {rel[m]['spearman_brown']:.2f}, n={rel[m]['n']})" if m in rel else "–" for m in ("unified/gain_bits", "native/gain_bits")])
    if rows:
        L += ["**R1: split-half reliability of the EEG-specific gain (first vs second half of each recording; SB = Spearman–Brown)**", "",
              table(["cell (full window)", "unified gain_bits", "native gain_bits"], rows), ""]
    L += ["## 7. Training diagnostics", ""]
    rows = []
    for ds in DSN:
        for o in OBJ:
            k = key("core", ds, o, MAIN_T[ds], "full"); c = full.get(k)
            if not c:
                continue
            ul = c["unit_level"].get("unified/gain_bits") or c["unit_level"].get("head_gain_vs_base_bits") or {}
            rows.append([f"{DSN[ds]} {o}", c["best_epoch_median"], c["best_epoch_iqr"], c["units_resumed"], f"{ul.get('n_positive')}/{ul.get('n')}",
                         f"{ul.get('sd'):.4f}" if ul.get("sd") is not None else "–"])
    L += [table(["cell (main target, full)", "best epoch median", "IQR", "units resumed", "units with positive mean", "unit-level SD"], rows), ""]
    return "\n".join(L)


def optimization_results(full, C):
    L = ["# Kernel CS-QMI full round: optimisation and capacity (E5)", "",
         "Each variant changes one axis of the default configuration; paired difference vs the default core cell (same participants, seeds and folds).", ""]
    for ds, t in (("fau", "local"), ("private_bdf", "current_class")):
        m = "unified/gain_bits" if ds == "fau" else "head_gain_vs_base_bits"
        rows = []
        for k, v in sorted(C["optimization"].items()):
            q = k.split(" MINUS ")[0].split("|")
            if q[1] != ds:
                continue
            rows.append([q[2], q[5], f(g(full, k.split(" MINUS ")[0], "all", m), 4), f((v or {}).get(m, {}).get("all"), 4), cov(full, k.split(" MINUS ")[0])])
        for o in OBJ:
            rows.append([o, "default", f(g(full, key("core", ds, o, t, "full"), "all", m), 4), "0", cov(full, key("core", ds, o, t, "full"))])
        rows.sort(key=lambda r: (r[0], r[1]))
        L += [f"## {DSN[ds]} {t} / full, metric {m}", "", table(["method", "variant", "value", "variant − default", "coverage"], rows), ""]
    return "\n".join(L)


def temporal_results(full, C):
    L = ["# Kernel CS-QMI full round: temporal structure", "",
         "Windows per cohort as in spec §8.3. Δ_{L|E} = R(early) − R(joint), Δ_{E|L} = R(late) − R(joint), with R the query log loss (bits); positive = the other window adds to the first.", ""]
    for ds in DSN:
        t = MAIN_T[ds]
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        rows = [[w] + [f(g(full, key("core", ds, o, t, w), "all", m), 4) for o in OBJ] for w in WINS]
        rows += [["late_equalwidth"] + [f(g(full, key("equal_width", ds, o, t, "late_equalwidth"), "all", m), 4) for o in OBJ]]
        L += [f"## {DSN[ds]} {t}: {m} by window", "", table(["window"] + list(OBJ), rows), ""]
        if ds in ("fau", "dtu"):
            for tt in ("Ac", "Lz"):
                rows = [[w] + [f(g(full, key("core" if w == "full" else "ext_target_windows", ds, o, tt, w), "all", m), 4) for o in OBJ] for w in WINS]
                if any(c != "–" for r in rows[1:] for c in r[1:]):
                    L += [f"### {DSN[ds]} {tt} by window (early / late / joint from extension E12)", "", table(["window"] + list(OBJ), rows), ""]
        rows = []
        tkeys = [(o, t, key("core", ds, o, t, "joint")) for o in OBJ] + [(o, tt, key("ext_target_windows", ds, o, tt, "joint")) for tt in ("Ac", "Lz") for o in OBJ] \
            + ([(o, t, key("ext_class_balanced", ds, o, t, "joint")) for o in OBJ] if ds == "private_bdf" else [])
        for o, tt, kk in tkeys:
            v = C["temporal"].get(kk)
            if not v:
                continue
            for rk, d in v.items():
                for dn in ("Delta_L_given_E", "Delta_E_given_L"):
                    for grp, b in d[dn].items():
                        rows.append([f"{o} {tt}" + (" (balanced)" if kk.startswith("ext_class") else ""), rk.split("/")[0], dn, grp, f(b, 4)])
                for k2, b in d.items():
                    if k2.startswith("Delta") and " " in k2:
                        rows.append([f"{o} {tt}" + (" (balanced)" if kk.startswith("ext_class") else ""), rk.split("/")[0], k2, "group difference", f(b, 4)])
        L += [f"### {DSN[ds]}: Δ by group", "", table(["method target", "readout", "Δ", "group", "bits"], rows), ""]
    return "\n".join(L)


def group_results(full, C, D):
    L = ["# Kernel CS-QMI full round: groups, CI training coverage, development and function", ""]
    for ds in DSN:
        t = MAIN_T[ds]
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        gs = sorted({gg for o in OBJ for gg in ((full.get(key("core", ds, o, t, "full")) or {}).get("groups", {}))} - {"all"})
        rows = [[o] + [f(g(full, key("core", ds, o, t, "full"), gg, m), 4) for gg in gs] for o in OBJ]
        L += [f"## {DSN[ds]} {t}/full: {m} by group", "", table(["method"] + gs, rows), ""]
        rows = []
        for o in OBJ:
            for w in WINS:
                for gk, mm in (C["groups"].get(key("core", ds, o, t, w)) or {}).items():
                    rows.append([o, w, gk, f(mm.get(m), 4)])
        L += [f"### {DSN[ds]}: group differences ({m})", "", table(["method", "window", "contrast", "difference"], rows), ""]
    L += ["## CI training coverage (E7): TH+HA-trained minus jointly trained (TH+HA+CI), same test panel", ""]
    rows = []
    for k, v in sorted(C["exclude_CI_training"].items()):
        q = k.split(" MINUS ")[0].split("|")
        for gg in ("ci", "ha", "th", "all"):
            rows.append([q[2], q[3], gg, f((v or {}).get("unified/gain_bits", {}).get(gg), 4), f((v or {}).get("native/gain_bits", {}).get(gg), 4)])
    L += [table(["method", "target", "test group", "Δ unified gain_bits", "Δ native gain_bits"], rows), ""]
    L += ["## Development (spec §11.2)", "", "Private: per window, OLS of the child-level value on calendar age (months) and HA; HA only: age and device-use duration.", ""]
    rows = []
    for o, res in D.get("private_development", {}).items():
        for y, r in res.items():
            for w, pw in r["per_window"].items():
                c1 = pw["age_slope_all"].get("coef", {}); c2 = pw["HA_age_duration"].get("coef", {})
                rows.append([o, y, w, f(c1.get("age_months"), 5), f(c1.get("HA"), 4), f(c2.get("age_months"), 5), f(c2.get("duration_months"), 5)])
    L += [table(["method", "outcome", "window", "age slope (all)", "HA − NH", "age slope (HA)", "duration slope (HA)"], rows), ""]
    rows = []
    for k, r in D.get("federici_development", {}).items():
        if not isinstance(r, dict):
            continue
        for kk, v in r.items():
            rows.append([k, kk, f(v.get("coef", {}).get("age_years"), 4), v.get("n")])
    L += ["Federici: OLS slope of the participant-level gain on age (years), within group.", "", table(["method|window", "outcome|group", "age slope", "n"], rows), ""]
    L += ["## Function (spec §11.3): C → C + overall alignment → C + overall + temporal structure", "",
          "LOO-OLS squared-error risk; differences are bigger − smaller model (negative = the added block improves held-out prediction).", ""]
    rows = []
    for k, v in sorted(D.get("function", {}).items()):
        if not isinstance(v, dict) or "n" not in v:
            continue
        rows.append([k, v["n"], f(v.get("step1_minus_step0"), 3), f(v.get("step2_minus_step1"), 3)])
    L += [table(["endpoint", "n", "+overall", "+temporal structure"], rows), ""]
    return "\n".join(L)


def figures(full, C):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    os.makedirs(FIG, exist_ok=True)
    cols = {"NCE": "#4C72B0", "FMCA": "#55A868", "CS_SINGLE": "#C44E52", "CS_MULTI": "#8172B2"}
    # 1. core gain by window
    fig, axs = plt.subplots(1, 4, figsize=(16, 3.6))
    for ax, ds in zip(axs, DSN):
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        for j, o in enumerate(OBJ):
            for i, w in enumerate(WINS):
                b = g(full, key("core", ds, o, MAIN_T[ds], w), "all", m)
                if b and b.get("est") is not None:
                    x = i + (j - 1.5) * 0.18
                    ax.bar(x, b["est"], 0.17, color=cols[o], label=o if i == 0 else None)
                    if "ci_low" in b:
                        ax.plot([x, x], [b["ci_low"], b["ci_high"]], "k-", lw=0.8)
        ax.axhline(0, color="k", lw=0.5); ax.set_xticks(range(4)); ax.set_xticklabels(WINS); ax.set_title(f"{DSN[ds]} ({m})", fontsize=9)
    axs[0].legend(fontsize=7); fig.tight_layout(); fig.savefig(os.path.join(FIG, "core_gain_by_window.png"), dpi=130); plt.close(fig)
    # 2. learning curves (median selection score)
    fig, axs = plt.subplots(1, 4, figsize=(16, 3.4))
    for ax, ds in zip(axs, DSN):
        for o in OBJ:
            c = (full.get(key("core", ds, o, MAIN_T[ds], "full")) or {}).get("curve_median", {})
            if c:
                ep = sorted(int(e) for e in c)
                y = [c[str(e)].get("selection_score", [np.nan] * 3)[1] for e in ep]
                ax.plot(ep, y, color=cols[o], label=o)
        ax.set_title(f"{DSN[ds]}: median selection score", fontsize=9); ax.set_xlabel("epoch")
    axs[0].legend(fontsize=7); fig.tight_layout(); fig.savefig(os.path.join(FIG, "learning_curves.png"), dpi=130); plt.close(fig)
    # 3. groups
    fig, axs = plt.subplots(1, 4, figsize=(16, 3.4))
    for ax, ds in zip(axs, DSN):
        m = "unified/gain_bits" if ds != "private_bdf" else "head_gain_vs_base_bits"
        gs = sorted({gg for o in OBJ for gg in ((full.get(key("core", ds, o, MAIN_T[ds], "full")) or {}).get("groups", {}))} - {"all"})
        for j, o in enumerate(OBJ):
            for i, gg in enumerate(gs):
                b = g(full, key("core", ds, o, MAIN_T[ds], "full"), gg, m)
                if b and b.get("est") is not None:
                    x = i + (j - 1.5) * 0.18
                    ax.bar(x, b["est"], 0.17, color=cols[o], label=o if i == 0 else None)
                    if "ci_low" in b:
                        ax.plot([x, x], [b["ci_low"], b["ci_high"]], "k-", lw=0.8)
        ax.axhline(0, color="k", lw=0.5); ax.set_xticks(range(len(gs))); ax.set_xticklabels(gs); ax.set_title(f"{DSN[ds]} full ({m})", fontsize=9)
    axs[0].legend(fontsize=7); fig.tight_layout(); fig.savefig(os.path.join(FIG, "groups_full_window.png"), dpi=130); plt.close(fig)


def main():
    full = json.load(open(os.path.join(RES, "full_results.json")))
    C = json.load(open(os.path.join(RES, "contrasts.json")))
    D = json.load(open(os.path.join(RES, "development_function.json")))
    man = json.load(open(os.path.join(RES, "RUN_MANIFEST_summary.json")))
    os.makedirs(DOC, exist_ok=True)
    for name, txt in (("FULL_RESULTS.md", full_results(full, C, man)), ("OPTIMIZATION_RESULTS.md", optimization_results(full, C)),
                      ("TEMPORAL_RESULTS.md", temporal_results(full, C)), ("GROUP_DEVELOPMENT_RESULTS.md", group_results(full, C, D))):
        open(os.path.join(DOC, name), "w").write(txt + "\n")
    figures(full, C)
    print("written", DOC)


if __name__ == "__main__":
    main()
